### ISSUE TITLE
eventListener on click rather than submit

### ISSUE THREAD

**Issue by ZooeyMiller** [Jen-Harris/Tentacular#25]
The event listener for when you make the request to your back end is attached to the button on click, if you changed this to wrap the input, button etc in a form and ran the event on submit then hitting enter when in the box would also run the eventListener, it's a bit more semantic and also makes it easier for keyboard users.

**Comment by Jen-Harris** [comment]
Hey Zooey, thanks for the feedback. 
I don't think we fully understand! It seems that it already works when using enter without changing anything?

**Comment by ZooeyMiller** [comment]
So if I use tab to select the button then pressing enter will work, but if you make it all into a form, and then attach the eventListener to the form, with a trigger of "submit" then I can press enter when I've still got focus on the input and it will work.

**Comment by morkeltry** [comment]
tick :)
