### ISSUE TITLE
empty file

### ISSUE THREAD

**Issue by ZooeyMiller** [Jen-Harris/Tentacular#34]
you have an empty file (`apiRequest.js`), I don't think it would be a bad idea to have this file to contain the logic for making your request on the back end, to make your code even more modular, but if you've decided not to do this then you should remove this file.

**Comment by rachaelcodes** [comment]
and https://github.com/Jen-Harris/Tentacular/blob/master/images/octopus.png is cute - would be a shame not to use it!
