### ISSUE TITLE
Wonderful job!

### ISSUE THREAD

**Issue by azayneeva** [Jen-Harris/Tentacular#35]
Guys, it's a pleasure to read your code! Logic of the code is easy to follow, code is clean and comments are helpful! And what's more - your app is so useful! I think I will even use it later to search for github repos! Wonderful job, guys! :)

**Comment by ZooeyMiller** [comment]
I agree, you've done a great job on this!

**Comment by Jen-Harris** [comment]
Thank you @azayneeva :kissing_heart:
